export enum LinkType {
  COMMUNICATION = 'COMMUNICATION',
  ASSOCIATION = 'ASSOCIATION',
  COLOCATION = 'COLOCATION',
  FINANCIAL = 'FINANCIAL',
  ORGANIZATIONAL = 'ORGANIZATIONAL',
  MOVEMENT_PATTERN = 'MOVEMENT_PATTERN',
  COMMAND_CONTROL = 'COMMAND_CONTROL',
}
