export enum AlertType {
  GEOFENCE_ENTRY = 'GEOFENCE_ENTRY',
  GEOFENCE_EXIT = 'GEOFENCE_EXIT',
  SPEED_ANOMALY = 'SPEED_ANOMALY',
  PROXIMITY = 'PROXIMITY',
  PATTERN_MATCH = 'PATTERN_MATCH',
  CUSTOM = 'CUSTOM',
}

export enum AlertSeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum RuleType {
  GEOFENCE = 'GEOFENCE',
  SPEED_THRESHOLD = 'SPEED_THRESHOLD',
  PROXIMITY = 'PROXIMITY',
  PATTERN = 'PATTERN',
}
